# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'incognitoApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for incognitoApp
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  target 'incognitoAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
